server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teach_competition?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 147258369
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

#七牛云OSS
qiniu:
  accessKey: cZMuSkVZEGGWw1Fk27P1Hp1UYj98ae3hznRXjU6r
  secretKey: sVOfod5SBFvMr_MQk4jZ9nWRmByz-KuSJYpUvjoG
  bucket: teachcompetition
  urlPrefix: http://sf9cmkal1.hd-bkt.clouddn.com
  region: z0   # 替换为你的七牛云地区，这里是华东-浙江
